name: "SOPS Secrets Decryption"
author: "Replicate"
description: |-
  This action decrypts secrets using SOPS and in the post step, cleans the decrypted secrets.

inputs:
  source_dir:
    description: "The directory containing the encrypted secrets files"
    required: true
  file_pattern:
    description: "The pattern to match the encrypted secrets files"
    required: true
  dest_dir:
    description: "The directory to write the decrypted secrets files"
    required: true
  create_dest_dir:
    description: "Whether to create the destination directory if it does not exist"
    required: true
  delete_dest_dir:
    description: "Whether to remove the destination directory in post"
    required: true

runs:
  using: 'node20'
  main: "dist/main/index.js"
  post: "dist/post/index.js"


