name: Deploy to CoreWeave

# If you want to use SOPS, this workflow will use workload identity federation.
# That will require that the appropriate policy binding has been set up for the
# calling repository. See if it has with:
#
#     gcloud iam service-accounts get-iam-policy deploy@replicate-production.iam.gserviceaccount.com
#
# Note that the calling workflow will also need to specify the appropriate
# permissions on the job that uses this workflow, e.g.
#
#     deploy:
#       permissions:
#         contents: 'read'
#         id-token: 'write'
#       uses: replicate/workflows/.github/workflows/deploy-to-coreweave.yml@main

on:
  workflow_call:
    inputs:
      run:
        required: true
        type: string
        description: The deployment command to run
      honeycomb_dataset:
        required: true
        type: string
        description: The name of the Honeycomb dataset used for the deployment marker
      install_helm:
        required: false
        type: boolean
        description: Whether this deployment needs helm to be installed (installs helm-secrets if install_sops is also specified)
        default: false
      install_kustomize:
        required: false
        type: boolean
        description: Whether this deployment needs the kustomize CLI to be installed
        default: false
      install_sops:
        required: false
        type: boolean
        description: Whether this deployment needs SOPS to be installed
        default: false
    secrets:
      COREWEAVE_KUBECONFIG:
        required: true
      HONEYCOMB_API_KEY:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'push') && format('refs/heads/{0}', github.event.repository.default_branch) }}

    env:
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      COMMIT_URL: ${{ github.event.head_commit.url }}

    steps:
      - uses: actions/checkout@master

      - name: Install credentials
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.COREWEAVE_KUBECONFIG }}

      # We log into GCP for access to SOPS keys
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        if: ${{ inputs.install_sops }}
        with:
          workload_identity_provider: projects/1025538909507/locations/global/workloadIdentityPools/github/providers/github-actions
          service_account: deploy@replicate-production.iam.gserviceaccount.com

      - name: Install sops
        if: ${{ inputs.install_sops }}
        uses: mdgreenwald/mozilla-sops-action@v1.4.1
        with:
          version: 'v3.7.3'

      - name: Install helm
        if: ${{ inputs.install_helm }}
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.1'

      - name: Install helm-secrets
        if: ${{ inputs.install_helm && inputs.install_sops }}
        run: helm plugin install https://github.com/jkroepke/helm-secrets --version v4.4.2

      - name: Install kustomize
        if: ${{ inputs.install_kustomize }}
        run: |-
          mkdir -p "$HOME/.local/bin"
          curl -sfL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.0.0/kustomize_v5.0.0_linux_amd64.tar.gz | tar -zx -C "$HOME/.local/bin"
          chmod +x "$HOME/.local/bin/kustomize"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Add marker to Honeycomb
        run: |-
          <<<"$COMMIT_MESSAGE" read -r message_first_line
          curl "https://api.honeycomb.io/1/markers/${{ inputs.honeycomb_dataset }}" \
            -sSL \
            -X POST \
            -H "X-Honeycomb-Team: ${{ secrets.HONEYCOMB_API_KEY }}" \
            -d '{"type": "deploy", "message": "[coreweave] '"$message_first_line"'", "url": "'"$COMMIT_URL"'"}'

      - name: Deploy
        run: ${{ inputs.run }}
